steps:
# deploy container image to Cloud Run
 - id: deploy
   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'SERVICE-NAME'
   - '--image'
   - 'gcr.io/$PROJECT_ID/next-2021-app:$COMMIT_SHA'
   - '--region'
   - 'REGION'
options:
  workerPool: 'projects/agmsb-k8s/locations/us-west1/workerPools/sandbox-privatepool'
